authapp/urls.py
from django.urls import path
from authapp.views import AuthLoginView, AuthLogoutView, UpdateProfileView, DeleteProfileView, \
	CreateProfileView
app_name = 'authapp'

urlpatterns = [
	path('login/', AuthLoginView.as_view(), name='login'),
	path('logout/', AuthLogoutView.as_view(), name='logout'),
	path('updateuser/', UpdateProfileView.as_view(), name='update'),
	path('deleteuser/<int:pk>', DeleteProfileView.as_view(), name='delete'),
	path('registration/', CreateProfileView.as_view(), name='registration'),
]

basketapp/urls.py
from django.urls import path
from basketapp.views import OrdersView, BasketView, RemoveFromBasketView, DeleteBasketView
import os

app_name = 'basketapp'

urlpatterns = [
	path('orders/', OrdersView.as_view(), name='orders'),
	path('orders/<int:pk>/', BasketView.as_view(), name='basket'),
	path('remove/<int:pk>/', RemoveFromBasketView.as_view(), name='remove'),
	path('delete/<int:pk>/', DeleteBasketView.as_view(), name='delete'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^', include('shopapp.urls', namespace='shop')),
    re_path(r'^rosetta/', include('rosetta.urls')),
    path('shop/', include('shopapp.urls', namespace='shop')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    ]
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopapp/urls.py
from django.urls import path
from shopapp.views import MainListView, CatalogueListView, ContactsListView, AuthView, ProductCreateView, ProductDeleteView, \
 ChangeProductView, UpdateProductImageView, ProductView
import os
# OrderRedirectView, CreateOrderView


app_name = 'shopapp'

urlpatterns = [
    path('', MainListView.as_view(), name='main'),
    path('catalogue/', CatalogueListView.as_view(), name='catalogue'),
    path('product/<int:pk>/', ProductView.as_view(), name='product'),
    path('catalogue/category/<int:pk>/', CatalogueListView.as_view(), name='category'),
    path('contacts/', ContactsListView.as_view(), name='contacts'),
    path('product/update/<int:pk>/', ChangeProductView.as_view(), name='update'),
    path('update_image/product/<int:pk>/<slug:slug>/', UpdateProductImageView.as_view(), name='image'),
    path('add_product/', ProductCreateView.as_view(), name='add'),
    path('index/', MainListView.as_view(), name='main'),
    path('auth/', AuthView.as_view(), name='auth'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='delete')
    ]

basketapp/models.py
from django.db import models
from django.conf import settings
from shopapp.models import Product
from django.utils.translation import ugettext_lazy as _

# Create your models here.

class BasketManager(models.Manager):

	def get_active(self, user):
		return self.filter(status=True, user=user)

	def get_order(self, user):
		return self.get_active(user=user)[0]


class BasketItemManager(models.Manager):

	def orders_list(self, order):
		return self.filter(order_id=order).values_list('product', flat=True)


class Basket(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	order_date = models.DateField(verbose_name=_('Date'), auto_now_add=True)
	status = models.BooleanField('open', default=True)

	objects = BasketManager()


class BasketItem(models.Model):
	order_id = models.ForeignKey(Basket, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	quantity = models.PositiveIntegerField(verbose_name=_('quantity'), default=1)
	add_datetime = models.DateTimeField(verbose_name=_('time'), auto_now_add=True)

	objects = BasketItemManager()

basketapp/forms.py
from django.forms import ModelForm, Select, ChoiceField
from basketapp.models import BasketItem

class AddProductForm(ModelForm):
	class Meta:
		model = BasketItem
		fields = ['quantity']

	def __init__(self, *args, **kwargs):
	        super().__init__(*args, **kwargs)
	        for field_name, field in self.fields.items():
	        	print(field.widget.attrs)
	        	if field_name == 'quantity':
	        		field.widget.attrs.update({'class':'quantity'})
	        		print(field.widget.attrs)

basketapp/views.py
from django.http import HttpResponseRedirect
from basketapp.models import Basket, BasketItem
from django.forms import Form
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from basketapp.forms import AddProductForm
from django.urls import reverse_lazy

# Create your views here.

class OrdersView(LoginRequiredMixin, ListView):
	'''Represent list of active orders'''
	login_url = reverse_lazy('authapp:login')
	model = Basket

	def get_context_data(self, **kwargs):
		context = super(OrdersView, self).get_context_data(**kwargs)
		context['orders'] = Basket.objects.filter(user=self.request.user)
		context['counter'] = context['orders'].count()
		return context

class BasketView(LoginRequiredMixin, ListView):
	'''Represent items in active order'''
	login_url = reverse_lazy('authapp:login')
	model = BasketItem

	def get_queryset(self):
		queryset = BasketItem.objects.filter(order_id=self.kwargs['pk'])
		return queryset

	def get_context_data(self, **kwargs):
		context = super(BasketView, self).get_context_data(**kwargs)
		items = self.get_queryset()
		total_sum = sum([int(item.product.price) * item.quantity for item in items])
		total_quantity = sum([item.quantity for item in items])
		headlines = ['Product', 'Image', 'Quantity', 'Price']
		context.update({'total_sum': total_sum, 'total_quantity': total_quantity, 'headlines': headlines})
		return context


class DeleteBasketView(LoginRequiredMixin, DeleteView):
	'''Class that delete order'''
	login_url = reverse_lazy('authapp:login')
	model = Basket
	success_url = reverse_lazy('shopapp:catalogue')


class RemoveFromBasketView(LoginRequiredMixin, DeleteView):
	'''Class that delete item from order'''
	login_url = reverse_lazy('authapp:login')
	model = BasketItem

	def get_success_url(self):
		order = Basket.objects.get(user=self.request.user, status=True)
		if BasketItem.objects.filter(order_id=order).count() == 1:
			order.delete()
			return reverse_lazy('shopapp:main')
		else:
			return reverse_lazy('basketapp:basket', kwargs={'pk':order.id})
		

basketapp/templates/basketapp/includes/basket_list.html
{% load staticfiles %}
{% load to_num %}
{% load i18n %}

<div class="table_row">
	{% for word in headlines %}
		<div class="table_col">
			<p>{{ word }}</p>
		</div>
	{% endfor %}
</div>
{% for item in object_list %}
	<div class="table_row">
		<div class="table_col">
			<p>{{ item.product.brand }}</p>
			<p>{{ item.product.name }}</p>
		</div>
		<div class="table_col"><img src="{{ item.product.image.url }}" alt="{{ item.product.brand }}"></div>
		<div class="table_col">
			<div class="quant">
				<input type="number" name="quantity" min="0" max="20" value="{{ item.quantity }}">
				<form class="delete_item" action="{% url 'basketapp:remove' item.id %}" method="post">
						{% csrf_token %}
						{{ form }}
						<input class="button_link" type="submit" value="{% trans 'Delete item' %}">
				</form>
			</div>
		</div>
		<div class="table_col">{{ item.product.price|to_num }}</div>
	</div>
{% endfor %}

basketapp/templates/basketapp/includes/order_list.html
{% load staticfiles %}
{% load i18n %}

<div class="orders">
	{% if counter != 0 %}
		<h3>{% trans 'Your orders' %}</h3>
		{% for order in orders %}
			<div class="basket_row order">
				<p>{% trans 'Order ID ' %}{{ order.id }}</p>
				<a class="button_link" href="{% url 'basketapp:basket' order.id %}">{% trans 'Order info' %}</a>
				<form class="prod_delete_form" action="{% url 'basketapp:delete' order.id %}" method="post">
		            {% csrf_token %}
					<input class="button_link" type="submit" value="{% trans 'Delete order' %}">
	        	</form>
			</div>
		{% endfor %}
	{% else %}
		<div class="no_orders">
			<div class="note">
				<p>You have not orders at this moment<p>
				<p>To create order go to catalogue, choose product and push "Add to basket" button<p>
				<p>Order will be created immediately and product will be added to basket<p>
			</div>
			<a class="button_link" href="{% url 'shopapp:catalogue' %}">{% trans 'Go to catalogue' %}</a>
		</div>
	{% endif %}
</div>