authapp/urls.py
from django.urls import path
from authapp.views import AuthLoginView, AuthLogoutView, UpdateProfileView, DeleteProfileView, \
	CreateProfileView
app_name = 'authapp'

urlpatterns = [
	path('login/', AuthLoginView.as_view(), name='login'),
	path('logout/', AuthLogoutView.as_view(), name='logout'),
	path('updateuser/', UpdateProfileView.as_view(), name='update'),
	path('deleteuser/<int:pk>', DeleteProfileView.as_view(), name='delete'),
	path('registration/', CreateProfileView.as_view(), name='registration'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^', include('shopapp.urls', namespace='shop')),
    re_path(r'^rosetta/', include('rosetta.urls')),
    path('shop/', include('shopapp.urls', namespace='shop')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    ]
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopapp/urls.py
from django.urls import path
from shopapp.views import MainListView, CatalogueListView, ContactsListView, AuthView, ProductCreateView, ProductDeleteView, \
 ChangeProductView, UpdateProductImageView, ProductView
import os
# OrderRedirectView, CreateOrderView


app_name = 'shopapp'

urlpatterns = [
    path('', MainListView.as_view(), name='main'),
    path('catalogue/', CatalogueListView.as_view(), name='catalogue'),
    path('product/<int:pk>/', ProductView.as_view(), name='product'),
    path('catalogue/category/<int:pk>/', CatalogueListView.as_view(), name='category'),
    path('contacts/', ContactsListView.as_view(), name='contacts'),
    path('product/update/<int:pk>/', ChangeProductView.as_view(), name='update'),
    path('update_image/product/<int:pk>/<slug:slug>/', UpdateProductImageView.as_view(), name='image'),
    path('add_product/', ProductCreateView.as_view(), name='add'),
    path('index/', MainListView.as_view(), name='main'),
    path('auth/', AuthView.as_view(), name='auth'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='delete')
    ]

shopapp/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class Core(models.Model):
	sort = models.IntegerField('sort', default=0, null=True)
	active = models.BooleanField('active', default=False)

class ProductCategory(Core):

    class Meta:
        verbose_name = _('Product category')
        verbose_name_plural = _('Product categories')

    name = models.CharField(verbose_name=_('Category name'), max_length=64, unique=True)
    description = models.TextField(verbose_name=_('Category description'), blank=True)

    def __str__(self):
        return self.name

class Manufacturer(Core):
    """Класс отображающий таблицу 'Производитель' в базе данных"""
    class Meta:
        verbose_name = _('Manufacturer')
        verbose_name_plural = _('Manufacturers')

    name = models.CharField(verbose_name=_('Manufacturer name'), max_length=128)

    def __str__(self):
        return self.name

class Product(Core):

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name=_('product name'), max_length=128)
    image = models.ImageField(upload_to='products_images', verbose_name=_('Small product picture'), blank=True, help_text= '')
    big_image = models.ImageField(upload_to='products_images', verbose_name=_('Big product picture'), blank=True, help_text= '')
    description = models.TextField(verbose_name=_('product description'), blank=True)
    price = models.DecimalField(verbose_name='price', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name=_('quantity on stock'), default=0)
    brand = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

    def get_absolute_url(self):
        return reverse('shopapp:catalogue')

shopapp/forms.py
from django.forms import ModelForm, Select, ChoiceField
from basketapp.models import BasketItem

class AddProductForm(ModelForm):
	class Meta:
		model = BasketItem
		fields = ['quantity']

	def __init__(self, *args, **kwargs):
	        super().__init__(*args, **kwargs)
	        self.fields['quantity'].widget.attrs.update({'class':'quantity'})

shopapp/views.py
from django.shortcuts import render
from django.utils.translation import ugettext_lazy as _
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from shopapp.models import Product, ProductCategory
from basketapp.models import Basket, BasketItem
# from django.forms import Form, FileInput
# from django import forms
from shopapp.forms import AddProductForm
# from django.views import View
# from django.views.generic.detail import SingleObjectMixin
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, ModelFormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# Create your views here.


class MainListView(ListView):
	"""Class that represent loading of main page with two random images from Product model"""
	model = Product
	template_name = 'shopapp/index.html'

	def get_context_data(self, **kwargs):
		context = super(MainListView, self).get_context_data(**kwargs)
		context['prod_a'], context['prod_b'] = self.get_queryset().order_by('?')[0:2] # ошибка если меньше двух товаров!!!
		return context


class CatalogueListView(ListView):
	"""Class that represent catalogue page and load data from Produc model"""
	model = Product
	paginate_by = 6
	paginate_orphans = 0
	product_columns = 3
	# включи чтобы убрать предупреждение
	ordering = ['id']

	def get_queryset(self):
		return super().get_queryset().filter(category_id=self.kwargs.get('pk')) if 'pk' in self.kwargs else super().get_queryset()

	def get_yelded_paginator(self, objects_for_pagination):
		paginator = self.paginator_class(objects_for_pagination, self.product_columns, self.paginate_orphans)
		for page_num in paginator.page_range:
			yield paginator.get_page(page_num)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(categories=ProductCategory.objects.all(), **kwargs)
		context['obj_pages'] = self.get_yelded_paginator(context['page_obj'] if context['is_paginated'] else context['object_list'])
		return context


class ChangeProductView(LoginRequiredMixin, UpdateView):
	"""Class that represent updating data for product"""
	model = Product
	login_url = reverse_lazy('authapp:login')
	fields = ['brand', 'name', 'category', 'price', 'quantity']
	success_url = reverse_lazy('shopapp:catalogue')


class UpdateProductImageView(LoginRequiredMixin, UpdateView):
	'''Class that represent updating image for product'''
	model = Product
	login_url = reverse_lazy('authapp:login')
	template_name = 'shopapp/update_image.html'
	success_url = reverse_lazy('shopapp:catalogue')

	def get_context_data(self, **kwargs):
		slug = self.kwargs['slug']
		self.fields = (slug, )
		context = super(UpdateProductImageView, self).get_context_data(**kwargs)
		context['image'] = getattr(self.object, slug)
		context['widget'] = context['form'].fields[slug].widget.render(slug, None)
		return context

class ProductView(LoginRequiredMixin, CreateView):
	'''Class that represent detail information about distinct product with 'add to basket' functionality'''
	model = Product
	login_url = reverse_lazy('authapp:login')
	template_name = 'shopapp/product_detail.html'
	form_class = AddProductForm

	def get_object(self):
		pk = self.kwargs['pk']
		obj = Product.objects.get(id=pk)
		return obj

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		obj = self.get_object()
		obj_id = getattr(obj, 'id', 0)
		cat_id = getattr(obj, 'category', 0)
		similar = Product.objects.exclude(id=obj_id).filter(category=cat_id)[:3]
		context.update({'object': obj, 'similar': similar})
		return context

	def form_valid(self, form):
		product = self.get_object()
		if Basket.objects.get_active(self.request.user).exists() == False:
			print(Basket.objects)
			new_order = Basket(user=self.request.user)
			new_order.save()
			return HttpResponseRedirect(self.get_success_url())
		elif Basket.objects.get_active(self.request.user):
			order_id = Basket.objects.get_order(self.request.user)
			if self.kwargs['pk'] in BasketItem.objects.orders_list(order_id):
				obj = BasketItem.objects.get(order_id=order_id, product=product)
				obj.quantity += int(self.request.POST.get('quantity'))
				obj.save()
				return HttpResponseRedirect(self.get_success_url())
			else:
				self.object = form.save(commit=False)
				self.object.product = product
				self.object.order_id = order_id
				self.object.quantity = int(self.request.POST.get('quantity'))
				self.object.save()
				return super(ModelFormMixin, self).form_valid(form)

	def get_success_url(self):
		order_id = Basket.objects.get_order(self.request.user)
		if self.kwargs['pk'] not in BasketItem.objects.orders_list(order_id):
			obj = BasketItem(order_id=order_id)
			obj.product = self.get_object()
			obj.quantity = int(self.request.POST.get('quantity'))
			obj.save()
			return reverse_lazy('basketapp:basket', kwargs={'pk':order_id.id})
		else:
			return reverse_lazy('basketapp:basket', kwargs={'pk':order_id.id})


class ContactsListView(TemplateView):
	"""Class that represent contacts page"""
	template_name = 'shopapp/contacts.html'


class AuthView(TemplateView):
	"""Class that represent page for choosing login or register redirect"""
	template_name = 'shopapp/auth.html'


class ProductCreateView(CreateView):
	"""Class that represent page for creating new record in Product model"""
	model = Product
	template_name_suffix = '_create_form'
	# template_name = 'shopapp/create_product_form.html'
	fields = ['brand', 'name', 'category', 'image', 'big_image', 'price', 'quantity']


class ProductDeleteView(LoginRequiredMixin, DeleteView):
	"""Class that represent page for deleting record from product model"""
	model = Product
	login_url = reverse_lazy('authapp:login')
	success_url = reverse_lazy('shopapp:catalogue')

shopapp/templates/shopapp/auth.html
{% extends "basic.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
    {% trans 'Authorization' %}
{% endblock title %}

{% block context %}
    <div class="auth">
    	<a class="button_link" href="{% url 'authapp:login' %}">{% trans 'Log in' %}</a>
    	<a class="button_link" href="{% url 'authapp:registration' %}">{% trans 'Create profile' %}</a>
    </div>
{% endblock context %}

shopapp/templates/shopapp/contacts.html
{% extends "basic.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
    {% trans 'Contacts' %}
{% endblock title %}

{% block context %}
    <div class="contacts">
        <h1>{% trans 'Contact us' %}</h1>
        <form action="#" target="_blank">
            <p>{% trans 'First name' %}</p>
            <input type="text" name="first_name" autofocus required>
            <p>{% trans 'Last name' %}</p>
            <input type="text" name="last_name" required>
            <p>{% trans 'Email' %}</p>
            <input type="email" name="email" placeholder="email@email.com" required>
            <p>{% trans 'Select a topic' %}</p>
            <select name="topics" id="topics">
                <option value="df">...</option>
                <option value="pr">{% trans 'About products' %}</option>
                <option value="sp">{% trans 'Support' %}</option>
                <option value="sh">{% trans 'Shipment' %}</option>
                <option value="ot">{% trans 'Other' %}</option>
            </select>
            <p>{% trans 'Please, enter some info here...' %}</p>
            <textarea cols="30" rows="10"></textarea>
            <input class="submit" type="submit" value="Submit">
        </form>
    </div>
{% endblock context %}

shopapp/templates/shopapp/index.html
{% extends "basic.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
    {% trans 'Main' %}
{% endblock title %}

{% block context %}
    <div class="welcome">
            <h2>{% trans 'Welcome in our sneakers online shop.' %}</h2>
            <h2>{% trans 'Here you can find a lot of sneakers with different designs from different brands.' %}</h2>
        <div class="products">
            <img src="{{ prod_a.big_image.url }}" alt="{{ prod_a.title }}">
            <img src="{{ prod_b.big_image.url }}" alt="{{ prod_b.title }}">
        </div>
            <a class="button_link" href="/catalogue/">{% trans 'Go to catalogue' %}</a>
    </div>
{% endblock context %}

shopapp/templates/shopapp/product_create_form.html
'{% extends "basic.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
    {% trans 'Create product' %}
{% endblock title %}

{% block context %}
    <div class="center">
        <form class="app_form" action="#" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <input class="button_link" type="submit" value="{% trans 'Post' %}">
        </form>
        <img src="" alt="">
    </div>
{% endblock context %}

shopapp/templates/shopapp/product_detail.html
{% extends "basic.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
    {% trans 'Detail' %}
{% endblock title %}

{% block context %}
    {% include 'shopapp/includes/distinct_product.html' %}
{% endblock context %}

shopapp/templates/shopapp/product_form.html
{% extends "basic.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
    {% trans 'Change product' %}
{% endblock title %}

{% block context %}
	<div class="update_form">
		<form class="app_form" action="#" method="post" enctype="multipart/form-data">
		    {% csrf_token %}
		    {{ form }}
		    <input class="button_link" type="submit" value="Post">
		</form>
		<div class="objects_images">
			<div class="image_block">
				<div class="big_img_box">
					<img src="{{ object.big_image.url }}" alt="{% trans 'big_image' %}">
				</div>
				<a href="{% url 'shopapp:image' object.id 'big_image' %}" class="button_link">{% trans 'Change big image' %}</a>
			</div>
			<div class="image_block">
				<div class="small_img_box">
					<img src="{{ object.image.url }}" alt="{% trans 'image' %}">
				</div>
					<a href="{% url 'shopapp:image' object.id 'image' %}" class="button_link">{% trans 'Change small image' %}</a>
			</div>
		</div>
	</div>
{% endblock context %}

shopapp/templates/shopapp/product_list.html
{% extends "basic.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
    {% trans 'Catalogue' %}
{% endblock title %}

{% block category %}
	{% include 'shopapp/includes/categories.html' %}
{% endblock%}

{% block context %}
    {% if user.is_authenticated %}
    	<a class="button_link" href="{% url 'shopapp:add' %}">{% trans 'Add product' %}</a>
    {% else %}
    {% endif %}
    <div class="catalogue">
        {% include 'shopapp/includes/test_cycle.html' with groups=object_list %}
    {% if is_paginated %}
    <ul class="paginate">
	      <li><a href="{% if page_obj.has_previous %}?page=1{% endif %}">First Page</a></li>
	      <li><a href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}">Previous Page</a></li>
	      <li><a>{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</a></li>
	      <li><a href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}">Next Page</a></li>
	      <li><a href="{% if page_obj.has_next %}?page={{ page_obj.paginator.num_pages }}{% endif %}">Last Page</a></li>
    </ul>
{% endif %}
    </div>

{% endblock context %}

shopapp/templates/shopapp/update_image.html
{% extends "basic.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
    {% trans 'Detail' %}
{% endblock title %}

{% block context %}
	<div class="update_form">
		<form class="app_form upd_im" action="#" method="post" enctype="multipart/form-data">
			{% csrf_token %}
		    {{ widget }}
			<input class="button_link" type="submit" value="Post">
		</form>
		<div class="img_container">
			<img src="{{ image.url }}" alt="{{image.field.verbose_name}}">
		</div>
	</div>
{% endblock context %}