authapp/urls.py
from django.urls import path
from authapp.views import AuthLoginView, AuthLogoutView, UpdateProfileView, DeleteProfileView, \
	CreateProfileView
app_name = 'authapp'

urlpatterns = [
	path('login/', AuthLoginView.as_view(), name='login'),
	path('logout/', AuthLogoutView.as_view(), name='logout'),
	path('updateuser/', UpdateProfileView.as_view(), name='update'),
	path('deleteuser/<int:pk>', DeleteProfileView.as_view(), name='delete'),
	path('registration/', CreateProfileView.as_view(), name='registration'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^', include('shopapp.urls', namespace='shop')),
    re_path(r'^rosetta/', include('rosetta.urls')),
    path('shop/', include('shopapp.urls', namespace='shop')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    ]
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopapp/urls.py
from django.urls import path
from shopapp.views import MainListView, CatalogueListView, ContactsListView, AuthView, ProductCreateView, ProductDeleteView, \
 ChangeProductView, UpdateProductImageView, ProductView
import os
# OrderRedirectView, CreateOrderView


app_name = 'shopapp'

urlpatterns = [
    path('', MainListView.as_view(), name='main'),
    path('catalogue/', CatalogueListView.as_view(), name='catalogue'),
    path('product/<int:pk>/', ProductView.as_view(), name='product'),
    path('catalogue/category/<int:pk>/', CatalogueListView.as_view(), name='category'),
    path('contacts/', ContactsListView.as_view(), name='contacts'),
    path('product/update/<int:pk>/', ChangeProductView.as_view(), name='update'),
    path('update_image/product/<int:pk>/<slug:slug>/', UpdateProductImageView.as_view(), name='image'),
    path('add_product/', ProductCreateView.as_view(), name='add'),
    path('index/', MainListView.as_view(), name='main'),
    path('auth/', AuthView.as_view(), name='auth'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='delete')
    ]

shopapp/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class Core(models.Model):
	sort = models.IntegerField('sort', default=0, null=True)
	active = models.BooleanField('active', default=False)

class ProductCategory(Core):

    class Meta:
        verbose_name = _('Product category')
        verbose_name_plural = _('Product categories')

    name = models.CharField(verbose_name=_('Category name'), max_length=64, unique=True)
    description = models.TextField(verbose_name=_('Category description'), blank=True)

    def __str__(self):
        return self.name

class Manufacturer(Core):
    """Класс отображающий таблицу 'Производитель' в базе данных"""
    class Meta:
        verbose_name = _('Manufacturer')
        verbose_name_plural = _('Manufacturers')

    name = models.CharField(verbose_name=_('Manufacturer name'), max_length=128)

    def __str__(self):
        return self.name

class Product(Core):

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name=_('product name'), max_length=128)
    image = models.ImageField(upload_to='products_images', verbose_name=_('Small product picture'), blank=True, help_text= '')
    big_image = models.ImageField(upload_to='products_images', verbose_name=_('Big product picture'), blank=True, help_text= '')
    description = models.TextField(verbose_name=_('product description'), blank=True)
    price = models.DecimalField(verbose_name='price', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name=_('quantity on stock'), default=0)
    brand = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

    def get_absolute_url(self):
        return reverse('shopapp:catalogue')

shopapp/forms.py
from django.forms import ModelForm, Select, ChoiceField
from basketapp.models import BasketItem

class AddProductForm(ModelForm):
	class Meta:
		model = BasketItem
		fields = ['quantity']

	def __init__(self, *args, **kwargs):
	        super().__init__(*args, **kwargs)
	        self.fields['quantity'].widget.attrs.update({'class':'quantity'})

shopapp/views.py
from django.shortcuts import render
from django.utils.translation import ugettext_lazy as _
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from shopapp.models import Product, ProductCategory
from basketapp.models import Basket, BasketItem
# from django.forms import Form, FileInput
# from django import forms
from shopapp.forms import AddProductForm
# from django.views import View
# from django.views.generic.detail import SingleObjectMixin
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, ModelFormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# Create your views here.


class MainListView(ListView):
	"""Class that represent loading of main page with two random images from Product model"""
	model = Product
	template_name = 'shopapp/index.html'

	def get_context_data(self, **kwargs):
		context = super(MainListView, self).get_context_data(**kwargs)
		context['prod_a'], context['prod_b'] = self.get_queryset().order_by('?')[0:2] # ошибка если меньше двух товаров!!!
		return context


class CatalogueListView(ListView):
	"""Class that represent catalogue page and load data from Produc model"""
	model = Product
	paginate_by = 6
	paginate_orphans = 0
	product_columns = 3
	# включи чтобы убрать предупреждение
	ordering = ['id']

	def get_queryset(self):
		return super().get_queryset().filter(category_id=self.kwargs.get('pk')) if 'pk' in self.kwargs else super().get_queryset()

	def get_yelded_paginator(self, objects_for_pagination):
		paginator = self.paginator_class(objects_for_pagination, self.product_columns, self.paginate_orphans)
		for page_num in paginator.page_range:
			yield paginator.get_page(page_num)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(categories=ProductCategory.objects.all(), **kwargs)
		context['obj_pages'] = self.get_yelded_paginator(context['page_obj'] if context['is_paginated'] else context['object_list'])
		return context


class ChangeProductView(LoginRequiredMixin, UpdateView):
	"""Class that represent updating data for product"""
	model = Product
	login_url = reverse_lazy('authapp:login')
	fields = ['brand', 'name', 'category', 'price', 'quantity']
	success_url = reverse_lazy('shopapp:catalogue')


class UpdateProductImageView(LoginRequiredMixin, UpdateView):
	'''Class that represent updating image for product'''
	model = Product
	login_url = reverse_lazy('authapp:login')
	template_name = 'shopapp/update_image.html'
	success_url = reverse_lazy('shopapp:catalogue')

	def get_context_data(self, **kwargs):
		slug = self.kwargs['slug']
		self.fields = (slug, )
		context = super(UpdateProductImageView, self).get_context_data(**kwargs)
		context['image'] = getattr(self.object, slug)
		context['widget'] = context['form'].fields[slug].widget.render(slug, None)
		return context

class ProductView(LoginRequiredMixin, CreateView):
	'''Class that represent detail information about distinct product with 'add to basket' functionality'''
	model = Product
	login_url = reverse_lazy('authapp:login')
	template_name = 'shopapp/product_detail.html'
	form_class = AddProductForm

	def get_object(self):
		pk = self.kwargs['pk']
		obj = Product.objects.get(id=pk)
		return obj

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		obj = self.get_object()
		obj_id = getattr(obj, 'id', 0)
		cat_id = getattr(obj, 'category', 0)
		similar = Product.objects.exclude(id=obj_id).filter(category=cat_id)[:3]
		context.update({'object': obj, 'similar': similar})
		return context

	def form_valid(self, form):
		product = self.get_object()
		if Basket.objects.get_active(self.request.user).exists() == False:
			print(Basket.objects)
			new_order = Basket(user=self.request.user)
			new_order.save()
			return HttpResponseRedirect(self.get_success_url())
		elif Basket.objects.get_active(self.request.user):
			order_id = Basket.objects.get_order(self.request.user)
			if self.kwargs['pk'] in BasketItem.objects.orders_list(order_id):
				obj = BasketItem.objects.get(order_id=order_id, product=product)
				obj.quantity += int(self.request.POST.get('quantity'))
				obj.save()
				return HttpResponseRedirect(self.get_success_url())
			else:
				self.object = form.save(commit=False)
				self.object.product = product
				self.object.order_id = order_id
				self.object.quantity = int(self.request.POST.get('quantity'))
				self.object.save()
				return super(ModelFormMixin, self).form_valid(form)

	def get_success_url(self):
		order_id = Basket.objects.get_order(self.request.user)
		if self.kwargs['pk'] not in BasketItem.objects.orders_list(order_id):
			obj = BasketItem(order_id=order_id)
			obj.product = self.get_object()
			obj.quantity = int(self.request.POST.get('quantity'))
			obj.save()
			return reverse_lazy('basketapp:basket', kwargs={'pk':order_id.id})
		else:
			return reverse_lazy('basketapp:basket', kwargs={'pk':order_id.id})


class ContactsListView(TemplateView):
	"""Class that represent contacts page"""
	template_name = 'shopapp/contacts.html'


class AuthView(TemplateView):
	"""Class that represent page for choosing login or register redirect"""
	template_name = 'shopapp/auth.html'


class ProductCreateView(CreateView):
	"""Class that represent page for creating new record in Product model"""
	model = Product
	template_name_suffix = '_create_form'
	# template_name = 'shopapp/create_product_form.html'
	fields = ['brand', 'name', 'category', 'image', 'big_image', 'price', 'quantity']


class ProductDeleteView(LoginRequiredMixin, DeleteView):
	"""Class that represent page for deleting record from product model"""
	model = Product
	login_url = reverse_lazy('authapp:login')
	success_url = reverse_lazy('shopapp:catalogue')

shopapp/templates/shopapp/includes/categories.html
{% load staticfiles %}
{% load i18n %}

<div class="category">
		<ul>
			{% for category in categories %}
					<li><a href="{% url 'shopapp:category' category.id %}">{{ category.name }}</a></li>
			{% endfor %}
		</ul>
</div>

shopapp/templates/shopapp/includes/cycle.html
{% load staticfiles %}
{% load i18n %}

{% for page in obj_pages %}
{{ page }} {{ page.object_list }}
    <div class="row">
        {% for product in page.object_list %}
            {% include 'shopapp/includes/product.html' %}
        {% endfor %}
    </div>
{% endfor %}

shopapp/templates/shopapp/includes/distinct_product.html
{% load staticfiles %}
{% load i18n %}


<div class="product">
    <div class="sneakers">
        <div class="sneakers_box">
            <img src="{{ object.big_image.url }}" alt="{{ object.name }}">
            <p>{% trans 'Similar products' %}</p>
            {% include 'shopapp/includes/similar_products.html' %}
        </div>
        <div class="desc">
            <h1>{{ object.brand }}</h1>
            <h4>{{ object.name }}</h4>
            <p>Sizes: 38-44</p>
            <div class="forms">
                <form class="add_to_basket" action="#" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input class="button_link" type="submit" value="{% trans 'Add to basket' %}">
                </form>
                <a href="{% url 'shopapp:update' object.id %}" class="button_link">{% trans 'Update product' %}</a>
                <form class="prod_delete_form" action="{% url 'shopapp:delete' object.id %}" method="post">
                    {% csrf_token %}
                    <input class="button_link" type="submit" value="{% trans 'Delete product' %}">
                </form>
            </div>
        </div>
    </div>
</div>

shopapp/templates/shopapp/includes/product.html
{% load staticfiles %}
{% load i18n %}

<div class="block">
    <a href="{% url 'shopapp:product' product.id %}">
   	<img src="{{product.image.url}}" alt="{{product.brand.name}}"></a>
    <p><span>{{product.brand.name}}</span></p>
    <p>{{product.name}}</p>
</div>

shopapp/templates/shopapp/includes/similar_products.html
{% load staticfiles %}
{% load i18n %}

<div class="similars">
	{% for product in similar %}
		<div class="sim">
			<a href="{% url 'shopapp:product' product.id %}">
				<img src="{{ product.image.url }}" alt="{{ product.brand }}">
			</a>
		</div>
	{% endfor %}
</div>

shopapp/templates/shopapp/includes/test_cycle.html
{% load staticfiles %}
{% load i18n %}

{% for page in obj_pages %}
    <div class="row">
        {% for product in page.object_list %}
            {% include 'shopapp/includes/product.html' %}
        {% endfor %}
    </div>
{% endfor %}