authapp/urls.py
from django.urls import path
from authapp.views import AuthLoginView, AuthLogoutView, UpdateProfileView, DeleteProfileView, \
	CreateProfileView
app_name = 'authapp'

urlpatterns = [
	path('login/', AuthLoginView.as_view(), name='login'),
	path('logout/', AuthLogoutView.as_view(), name='logout'),
	path('updateuser/', UpdateProfileView.as_view(), name='update'),
	path('deleteuser/<int:pk>', DeleteProfileView.as_view(), name='delete'),
	path('registration/', CreateProfileView.as_view(), name='registration'),
]

basketapp/urls.py
from django.urls import path
from basketapp.views import OrdersView, BasketView, RemoveFromBasketView, DeleteBasketView
import os

app_name = 'basketapp'

urlpatterns = [
	path('orders/', OrdersView.as_view(), name='orders'),
	path('orders/<int:pk>/', BasketView.as_view(), name='basket'),
	path('remove/<int:pk>/', RemoveFromBasketView.as_view(), name='remove'),
	path('delete/<int:pk>/', DeleteBasketView.as_view(), name='delete'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^', include('shopapp.urls', namespace='shop')),
    re_path(r'^rosetta/', include('rosetta.urls')),
    path('shop/', include('shopapp.urls', namespace='shop')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    ]
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopapp/urls.py
from django.urls import path
from shopapp.views import MainListView, CatalogueListView, ContactsListView, AuthView, ProductCreateView, ProductDeleteView, \
 ChangeProductView, UpdateProductImageView, ProductView
import os
# OrderRedirectView, CreateOrderView


app_name = 'shopapp'

urlpatterns = [
    path('', MainListView.as_view(), name='main'),
    path('catalogue/', CatalogueListView.as_view(), name='catalogue'),
    path('product/<int:pk>/', ProductView.as_view(), name='product'),
    path('catalogue/category/<int:pk>/', CatalogueListView.as_view(), name='category'),
    path('contacts/', ContactsListView.as_view(), name='contacts'),
    path('product/update/<int:pk>/', ChangeProductView.as_view(), name='update'),
    path('update_image/product/<int:pk>/<slug:slug>/', UpdateProductImageView.as_view(), name='image'),
    path('add_product/', ProductCreateView.as_view(), name='add'),
    path('index/', MainListView.as_view(), name='main'),
    path('auth/', AuthView.as_view(), name='auth'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='delete')
    ]

templates/basic.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <!--    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">-->
    <title>
        {% block title %}
            {% trans 'Sneakers shop' %}
        {% endblock title %}
    </title>
</head>

<body>
    <div class="header">
        {% if user.is_authenticated and user.avatar %}
        <div class="left_box">
            <img src="{{ user.avatar.url }}" alt="{% trans 'avatar' %}">
            <div class="text">
                <p>{% trans 'Hello' %}<br>
                {{ user.username }}</p>
            </div>
        </div>
        {% else %}
        <div class="empty_block"></div>
        {% endif %}
        <div class="log_menu">
            <a href="/"><img src="{% static 'img/Screenshot from 2018-09-02 21-34-39.png' %}" alt="{% trans 'emblem' %}"></a>
        <div class="menu">
            <ul>
                <li><a href="{% url 'shopapp:main' %}">{% trans 'Home' %}</a></li>
                <li><a href="{% url 'shopapp:catalogue' %}">{% trans 'Catalogue' %}</a></li>
                <li><a href="{% url 'shopapp:contacts' %}">{% trans 'Contacts' %}</a></li>
                <li><a href="{% url 'shopapp:auth' %}">{% trans 'Authorization' %}</a></li>
            </ul>
        </div>
        </div>
        {% if user.is_authenticated %}
            <div class="basket">
                <a href="{% url 'basketapp:orders' %}">{% trans 'Orders' %}</a>
                <a href="{% url 'authapp:logout' %}">{% trans 'Log out' %}</a>
                <a href="{% url 'authapp:update' %}">{% trans 'Change profile' %}</a>
            </div>
        {% else %}
            <div class="empty_block"></div>
        {% endif %}
    </div>
        {% block category %}
        {% endblock%}
    <div class="container">
        {% block context %}

        {% endblock context %}
    </div>
    <div class="footer">
        <p>&copy;{% trans 'Copyright - Sneakers 2018. All rights reserved.' %}</p>
        <!--     <div class="icon_links">
                <a href="#"><i class="fab fa-facebook-square"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-google-plus"></i></a>
                <a href="#"><i class="fab fa-pinterest"></i></a>
            </div> -->
        <div class="terms">
            <a href="#">{% trans 'Terms &amp; conditions' %}</a>
            <p>/</p>
            <a href="#">{% trans 'Privacy policy &amp; cookies' %}</a>
        </div>
    </div>
</body>

</html>